# Set addAssignees to 'author' to set the PR creator as the assignee.
name: 'Auto Assign'
on: 
  pull_request:
    branches: [ master ]

jobs:
  add-reviews:
    runs-on: macos-latest
    steps:
      - uses: auto-assign-action@v1.1.0
