name: Build

on:  
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn global add @vue/cli @vue/cli-service-global
      working-directory: .
    - name: remove node_modules and install
      run: |
          rm -rf node_modules/
          yarn install
    - run: yarn test:unit
    - run: yarn lint
    env:
      CI: true

        
